_name_or_path:
    value: facebook/esm2_t12_35M_UR50D
_wandb:
    value:
        cli_version: 0.19.8
        m:
            - "1": train/train_steps_per_second
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "1": train/epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/steps_per_second
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/total_flos
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/train_runtime
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/train_samples_per_second
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/train_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/learning_rate
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/runtime
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/samples_per_second
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 71
                - 98
            "2":
                - 1
                - 11
                - 49
                - 55
                - 71
                - 98
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.10.16
            "5": 0.19.8
            "6": 4.30.2
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - EsmForMaskedLM
attention_probs_dropout_prob:
    value: 0
auto_find_batch_size:
    value: false
bad_words_ids:
    value: null
begin_suppress_tokens:
    value: null
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: null
chunk_size_feed_forward:
    value: 0
classifier_dropout:
    value: null
cross_attention_hidden_size:
    value: null
data_seed:
    value: None
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 4
dataloader_pin_memory:
    value: true
ddp_backend:
    value: None
ddp_bucket_cap_mb:
    value: None
ddp_find_unused_parameters:
    value: None
ddp_timeout:
    value: 1800
debug:
    value: '[]'
decoder_start_token_id:
    value: null
deepspeed:
    value: None
disable_tqdm:
    value: false
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
early_stopping:
    value: false
emb_layer_norm_before:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: null
esmfold_config:
    value: null
eval_accumulation_steps:
    value: None
eval_batch_size:
    value: 16
eval_delay:
    value: 0
eval_steps:
    value: 500
evaluation_strategy:
    value: steps
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: true
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: '[]'
fsdp_config:
    value: '{''fsdp_min_num_params'': 0, ''xla'': False, ''xla_fsdp_grad_ckpt'': False}'
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: None
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 4
gradient_checkpointing:
    value: false
greater_is_better:
    value: false
group_by_length:
    value: false
half_precision_backend:
    value: auto
hidden_act:
    value: gelu
hidden_dropout_prob:
    value: 0
hidden_size:
    value: 480
hub_model_id:
    value: None
hub_private_repo:
    value: false
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_inputs_for_metrics:
    value: false
initializer_range:
    value: 0.02
intermediate_size:
    value: 1920
is_decoder:
    value: false
is_encoder_decoder:
    value: false
is_folding_model:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: None
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layer_norm_eps:
    value: 1e-05
learning_rate:
    value: 0.0004
length_column_name:
    value: length
length_penalty:
    value: 1
load_best_model_at_end:
    value: true
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: runs/esm_35m_ecoli_finetuning/runs/Mar17_02-10-41_kg03-p
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 500
logging_strategy:
    value: steps
lr_scheduler_type:
    value: cosine
mask_token_id:
    value: 32
max_grad_norm:
    value: 1
max_length:
    value: 20
max_position_embeddings:
    value: 1026
max_steps:
    value: -1
metric_for_best_model:
    value: loss
min_length:
    value: 0
model_type:
    value: esm
mp_parameters:
    value: ""
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 20
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 12
num_return_sequences:
    value: 1
num_train_epochs:
    value: 100
optim:
    value: adamw_hf
optim_args:
    value: None
output_attentions:
    value: false
output_dir:
    value: runs/esm_35m_ecoli_finetuning
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: 1
past_index:
    value: -1
per_device_eval_batch_size:
    value: 16
per_device_train_batch_size:
    value: 16
per_gpu_eval_batch_size:
    value: None
per_gpu_train_batch_size:
    value: None
position_embedding_type:
    value: rotary
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: None
push_to_hub_organization:
    value: None
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: false
repetition_penalty:
    value: 1
report_to:
    value: '[''wandb'']'
resume_from_checkpoint:
    value: None
return_dict:
    value: true
return_dict_in_generate:
    value: false
run_name:
    value: ESM2-35M-run-1
save_on_each_node:
    value: false
save_safetensors:
    value: false
save_steps:
    value: 500
save_strategy:
    value: steps
save_total_limit:
    value: 1
seed:
    value: 42
sep_token_id:
    value: null
sharded_ddp:
    value: '[]'
skip_memory_metrics:
    value: true
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: None
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
token_dropout:
    value: true
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: None
torch_compile_mode:
    value: None
torch_dtype:
    value: float32
torchdynamo:
    value: None
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: None
train_batch_size:
    value: 16
train_config:
    value:
        base_model: facebook/esm2_t12_35M_UR50D
        eval_path: ./dataset_splits/valid.fasta
        train_path: ./dataset_splits/train.fasta
        training_args:
            _n_gpu: 1
            adafactor: false
            adam_beta1: 0.9
            adam_beta2: 0.999
            adam_epsilon: 1e-08
            auto_find_batch_size: false
            bf16: false
            bf16_full_eval: false
            data_seed: null
            dataloader_drop_last: false
            dataloader_num_workers: 4
            dataloader_pin_memory: true
            ddp_backend: null
            ddp_bucket_cap_mb: null
            ddp_find_unused_parameters: null
            ddp_timeout: 1800
            debug: []
            deepspeed: null
            disable_tqdm: false
            do_eval: true
            do_predict: false
            do_train: false
            eval_accumulation_steps: null
            eval_delay: 0
            eval_steps: 500
            evaluation_strategy: STEPS
            fp16: true
            fp16_backend: auto
            fp16_full_eval: false
            fp16_opt_level: O1
            fsdp: []
            fsdp_config:
                fsdp_min_num_params: 0
                xla: false
                xla_fsdp_grad_ckpt: false
            fsdp_min_num_params: 0
            fsdp_transformer_layer_cls_to_wrap: null
            full_determinism: false
            gradient_accumulation_steps: 4
            gradient_checkpointing: false
            greater_is_better: false
            group_by_length: false
            half_precision_backend: auto
            hub_model_id: null
            hub_private_repo: false
            hub_strategy: EVERY_SAVE
            hub_token: null
            ignore_data_skip: false
            include_inputs_for_metrics: false
            jit_mode_eval: false
            label_names: null
            label_smoothing_factor: 0
            learning_rate: 0.0004
            length_column_name: length
            load_best_model_at_end: true
            local_rank: 0
            log_level: passive
            log_level_replica: warning
            log_on_each_node: true
            logging_dir: runs/esm_35m_ecoli_finetuning/runs/Mar17_02-10-41_kg03-p
            logging_first_step: false
            logging_nan_inf_filter: true
            logging_steps: 500
            logging_strategy: STEPS
            lr_scheduler_type: COSINE
            max_grad_norm: 1
            max_steps: -1
            metric_for_best_model: loss
            mp_parameters: ""
            no_cuda: false
            num_train_epochs: 100
            optim: ADAMW_HF
            optim_args: null
            output_dir: runs/esm_35m_ecoli_finetuning
            overwrite_output_dir: false
            past_index: -1
            per_device_eval_batch_size: 16
            per_device_train_batch_size: 16
            per_gpu_eval_batch_size: null
            per_gpu_train_batch_size: null
            prediction_loss_only: false
            push_to_hub: false
            push_to_hub_model_id: null
            push_to_hub_organization: null
            push_to_hub_token: null
            ray_scope: last
            remove_unused_columns: false
            report_to:
                - wandb
            resume_from_checkpoint: null
            run_name: ESM2-35M-run-1
            save_on_each_node: false
            save_safetensors: false
            save_steps: 500
            save_strategy: STEPS
            save_total_limit: 1
            seed: 42
            sharded_ddp: []
            skip_memory_metrics: true
            tf32: null
            torch_compile: false
            torch_compile_backend: null
            torch_compile_mode: null
            torchdynamo: null
            tpu_metrics_debug: false
            tpu_num_cores: null
            use_ipex: false
            use_legacy_prediction_loop: false
            use_mps_device: false
            warmup_ratio: 0
            warmup_steps: 1000
            weight_decay: 0.01
            xpu_backend: null
        wandb_project: esm_35m_ecoli_finetuning
transformers_version:
    value: 4.30.2
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: true
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_mps_device:
    value: false
vocab_list:
    value: null
vocab_size:
    value: 33
warmup_ratio:
    value: 0
warmup_steps:
    value: 1000
weight_decay:
    value: 0.01
xpu_backend:
    value: None
