#!/usr/bin/env python3
import argparse
from pathlib import Path
from enum import Enum
import yaml

MUTATIONS = ["F33I", "D58N", "Q72H", "A75V", "V85A", "V154F", "Y180F"]


def to_builtin(obj):
    """
    Convert Python/YAML objects from saved Trainer configs into plain YAML-safe
    values. This prevents !python/object tags from being written back out.
    """
    if isinstance(obj, dict):
        return {to_builtin(k): to_builtin(v) for k, v in obj.items()}

    if isinstance(obj, list):
        return [to_builtin(v) for v in obj]

    if isinstance(obj, tuple):
        return [to_builtin(v) for v in obj]

    if isinstance(obj, Enum):
        return obj.value

    if isinstance(obj, Path):
        return str(obj)

    if obj is None or isinstance(obj, (str, int, float, bool)):
        return obj

    # Some Transformers strategy objects are string-like or enum-like.
    if hasattr(obj, "value"):
        return obj.value

    return str(obj)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--template",
        default="pLM-ALE/runs/l40/progen2_151m_dgoa_cluster95_l40/train_config.yaml",
        help="Successful ProGen2 DgoA training config to use as template.",
    )
    parser.add_argument(
        "--outdir",
        default="pLM-ALE/configs/mutation_holdout/progen2_dgoa",
    )
    args = parser.parse_args()

    template_path = Path(args.template)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    if not template_path.exists():
        raise FileNotFoundError(template_path)

    # The template was generated by Transformers and contains Python tags,
    # so safe_load will fail. We load it, then sanitize it before writing.
    with open(template_path) as f:
        template = yaml.load(f, Loader=yaml.UnsafeLoader)

    template = to_builtin(template)

    for mut in MUTATIONS:
        cfg = dict(template)

        # These paths are relative to /project/massrl/silbadowell/pLM-ALE
        cfg["train_path"] = f"../data/mutation_holdout/dgoA/holdout_{mut}/train.faa"
        cfg["eval_path"] = f"../data/mutation_holdout/dgoA/holdout_{mut}/val.faa"
        cfg["test_path"] = f"../data/mutation_holdout/dgoA/holdout_{mut}/test_heldout_mutation.faa"

        cfg["wandb_project"] = "progen2_dgoa_mutation_holdout"
        cfg["wandb_notes"] = (
            f"DgoA leave-one-mutation-out ProGen2 fine-tuning. "
            f"Held-out mutation: {mut}."
        )

        cfg["heldout_mutation"] = mut

        if "training_args" not in cfg or cfg["training_args"] is None:
            cfg["training_args"] = {}

        cfg["training_args"] = to_builtin(cfg["training_args"])

        cfg["training_args"]["output_dir"] = (
            f"runs/mutation_holdout/progen2_151m_dgoa_holdout_{mut}_l40"
        )

        # Make sure these are plain strings if they came from Trainer enums.
        for key in [
            "evaluation_strategy",
            "eval_strategy",
            "save_strategy",
            "logging_strategy",
            "hub_strategy",
        ]:
            if key in cfg["training_args"]:
                cfg["training_args"][key] = to_builtin(cfg["training_args"][key])

        out = outdir / f"progen2_dgoa_holdout_{mut}.yml"

        with open(out, "w") as f:
            yaml.safe_dump(cfg, f, sort_keys=False)

        print(f"Wrote: {out}")


if __name__ == "__main__":
    main()
