_attn_implementation_autoset:
    value: true
_name_or_path:
    value: hugohrban/progen2-small
_wandb:
    value:
        cli_version: 0.19.8
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
                - 98
            "3":
                - 7
                - 19
                - 23
                - 55
                - 66
            "4": 3.13.2
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 5
            "9":
                "1": transformers_trainer
            "12": 0.19.8
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
activation_function:
    value: gelu_new
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - ProGenForCausalLM
attn_pdrop:
    value: 0
auto_find_batch_size:
    value: false
auto_map:
    value:
        AutoConfig: hugohrban/progen2-small--configuration_progen.ProGenConfig
        AutoModelForCausalLM: hugohrban/progen2-small--modeling_progen.ProGenForCausalLM
average_tokens_across_devices:
    value: false
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: 1
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 4
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
disable_tqdm:
    value: false
dispatch_batches:
    value: null
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
early_stopping:
    value: false
embd_pdrop:
    value: 0
embed_dim:
    value: 1024
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 2
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: 500
eval_strategy:
    value: steps
eval_use_gather_object:
    value: false
evaluation_strategy:
    value: steps
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: true
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 4
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: false
group_by_length:
    value: false
half_precision_backend:
    value: auto
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layer_norm_epsilon:
    value: 1e-05
learning_rate:
    value: 0.0004
length_column_name:
    value: length
length_penalty:
    value: 1
load_best_model_at_end:
    value: true
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: runs/progen2_151m_ecoli_finetuning_1/runs/Mar24_18-59-45_kg03-p
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 500
logging_strategy:
    value: steps
lr_scheduler_type:
    value: cosine
max_grad_norm:
    value: 1
max_length:
    value: 20
max_steps:
    value: -1
metric_for_best_model:
    value: loss
min_length:
    value: 0
model/num_parameters:
    value: 151541792
model_type:
    value: progen
mp_parameters:
    value: ""
n_embd:
    value: 1024
n_head:
    value: 16
n_inner:
    value: null
n_layer:
    value: 12
n_positions:
    value: 1024
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_return_sequences:
    value: 1
num_train_epochs:
    value: 100
optim:
    value: adamw_torch
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: runs/progen2_151m_ecoli_finetuning_1
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: null
past_index:
    value: -1
peft_config:
    value:
        default:
            auto_mapping: null
            base_model_name_or_path: hugohrban/progen2-small
            bias: none
            eva_config: null
            exclude_modules: null
            fan_in_fan_out: false
            inference_mode: false
            init_lora_weights: true
            layer_replication: null
            layers_pattern: null
            layers_to_transform: null
            lora_alpha: 16
            lora_bias: false
            lora_dropout: 0.1
            megatron_config: null
            megatron_core: megatron.core
            modules_to_save: null
            peft_type: LORA
            r: 8
            revision: null
            runtime_config:
                ephemeral_gpu_offload: false
            target_modules:
                - qkv_proj
            task_type: CAUSAL_LM
            use_dora: false
            use_rslora: false
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 8
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: false
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
resid_pdrop:
    value: 0
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
rotary_dim:
    value: 32
run_name:
    value: progen2-151M-run-1
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 500
save_strategy:
    value: steps
save_total_limit:
    value: 1
scale_attn_weights:
    value: true
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
split_batches:
    value: null
summary_activation:
    value: null
summary_first_dropout:
    value: 0.1
summary_proj_to_labels:
    value: true
summary_type:
    value: cls_index
summary_use_proj:
    value: true
suppress_tokens:
    value: null
task_specific_params:
    value:
        text-generation:
            do_sample: true
            max_length: 50
            temperature: 1
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: GPT2Tokenizer
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_dtype:
    value: float32
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
train_config:
    value:
        base_model: hugohrban/progen2-small
        eval_path: ./dataset_splits/finetuning_dataset/valid.fasta
        train_path: ./dataset_splits/finetuning_dataset/train.fasta
        training_args:
            _n_gpu: 1
            accelerator_config:
                dispatch_batches: null
                even_batches: true
                gradient_accumulation_kwargs: null
                non_blocking: false
                split_batches: false
                use_configured_state: false
                use_seedable_sampler: true
            adafactor: false
            adam_beta1: 0.9
            adam_beta2: 0.999
            adam_epsilon: 1e-08
            auto_find_batch_size: false
            average_tokens_across_devices: false
            batch_eval_metrics: false
            bf16: false
            bf16_full_eval: false
            data_seed: null
            dataloader_drop_last: false
            dataloader_num_workers: 4
            dataloader_persistent_workers: false
            dataloader_pin_memory: true
            dataloader_prefetch_factor: null
            ddp_backend: null
            ddp_broadcast_buffers: null
            ddp_bucket_cap_mb: null
            ddp_find_unused_parameters: null
            ddp_timeout: 1800
            debug: []
            deepspeed: null
            disable_tqdm: false
            dispatch_batches: null
            do_eval: true
            do_predict: false
            do_train: false
            eval_accumulation_steps: null
            eval_delay: 0
            eval_do_concat_batches: true
            eval_on_start: false
            eval_steps: 500
            eval_strategy: STEPS
            eval_use_gather_object: false
            evaluation_strategy: steps
            fp16: true
            fp16_backend: auto
            fp16_full_eval: false
            fp16_opt_level: O1
            fsdp: []
            fsdp_config:
                min_num_params: 0
                xla: false
                xla_fsdp_grad_ckpt: false
                xla_fsdp_v2: false
            fsdp_min_num_params: 0
            fsdp_transformer_layer_cls_to_wrap: null
            full_determinism: false
            gradient_accumulation_steps: 4
            gradient_checkpointing: false
            gradient_checkpointing_kwargs: null
            greater_is_better: false
            group_by_length: false
            half_precision_backend: auto
            hub_always_push: false
            hub_model_id: null
            hub_private_repo: null
            hub_strategy: EVERY_SAVE
            hub_token: null
            ignore_data_skip: false
            include_for_metrics: []
            include_inputs_for_metrics: false
            include_num_input_tokens_seen: false
            include_tokens_per_second: false
            jit_mode_eval: false
            label_names: null
            label_smoothing_factor: 0
            learning_rate: 0.0004
            length_column_name: length
            load_best_model_at_end: true
            local_rank: 0
            log_level: passive
            log_level_replica: warning
            log_on_each_node: true
            logging_dir: runs/progen2_151m_ecoli_finetuning_1/runs/Mar24_18-59-45_kg03-p
            logging_first_step: false
            logging_nan_inf_filter: true
            logging_steps: 500
            logging_strategy: STEPS
            lr_scheduler_type: COSINE
            max_grad_norm: 1
            max_steps: -1
            metric_for_best_model: loss
            mp_parameters: ""
            neftune_noise_alpha: null
            no_cuda: false
            num_train_epochs: 100
            optim: ADAMW_TORCH
            optim_args: null
            optim_target_modules: null
            output_dir: runs/progen2_151m_ecoli_finetuning_1
            overwrite_output_dir: false
            past_index: -1
            per_device_eval_batch_size: 8
            per_device_train_batch_size: 8
            per_gpu_eval_batch_size: null
            per_gpu_train_batch_size: null
            prediction_loss_only: false
            push_to_hub: false
            push_to_hub_model_id: null
            push_to_hub_organization: null
            push_to_hub_token: null
            ray_scope: last
            remove_unused_columns: false
            report_to:
                - wandb
            restore_callback_states_from_checkpoint: false
            resume_from_checkpoint: null
            run_name: progen2-151M-run-1
            save_on_each_node: false
            save_only_model: false
            save_safetensors: true
            save_steps: 500
            save_strategy: STEPS
            save_total_limit: 1
            seed: 42
            skip_memory_metrics: true
            split_batches: null
            tf32: null
            torch_compile: false
            torch_compile_backend: null
            torch_compile_mode: null
            torch_empty_cache_steps: null
            torchdynamo: null
            tpu_metrics_debug: false
            tpu_num_cores: null
            use_cpu: false
            use_ipex: false
            use_legacy_prediction_loop: false
            use_liger_kernel: false
            use_mps_device: false
            warmup_ratio: 0
            warmup_steps: 1000
            weight_decay: 0.01
        wandb_project: progen2_151m_ecoli_finetuning
transformers_version:
    value: 4.49.0
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: true
use_cpu:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_mps_device:
    value: false
vocab_size:
    value: 32
vocab_size_emb:
    value: 32
vocab_size_lm_head:
    value: 32
warmup_ratio:
    value: 0
warmup_steps:
    value: 1000
weight_decay:
    value: 0.01
