_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 71
                - 98
            "2":
                - 1
                - 11
                - 49
                - 55
                - 71
                - 98
            "3":
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.8
            "6": 4.30.2
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
train_config:
    value:
        base_model: facebook/esm2_t33_650M_UR50D
        eval_path: /home/idies/workspace/Storage/sdowell/persistent/ALEdb/BenchmarkingFinetuning/dataset_splits/valid.fasta
        train_path: /home/idies/workspace/Storage/sdowell/persistent/ALEdb/BenchmarkingFinetuning/dataset_splits/train.fasta
        training_args:
            _n_gpu: 1
            adafactor: false
            adam_beta1: 0.9
            adam_beta2: 0.999
            adam_epsilon: 1e-08
            auto_find_batch_size: false
            bf16: false
            bf16_full_eval: false
            data_seed: null
            dataloader_drop_last: false
            dataloader_num_workers: 4
            dataloader_pin_memory: true
            ddp_backend: null
            ddp_bucket_cap_mb: null
            ddp_find_unused_parameters: null
            ddp_timeout: 1800
            debug: []
            deepspeed: null
            disable_tqdm: false
            do_eval: true
            do_predict: false
            do_train: false
            eval_accumulation_steps: null
            eval_delay: 0
            eval_steps: 500
            evaluation_strategy: STEPS
            fp16: true
            fp16_backend: auto
            fp16_full_eval: false
            fp16_opt_level: O1
            fsdp: []
            fsdp_config:
                fsdp_min_num_params: 0
                xla: false
                xla_fsdp_grad_ckpt: false
            fsdp_min_num_params: 0
            fsdp_transformer_layer_cls_to_wrap: null
            full_determinism: false
            gradient_accumulation_steps: 4
            gradient_checkpointing: false
            greater_is_better: false
            group_by_length: false
            half_precision_backend: auto
            hub_model_id: null
            hub_private_repo: false
            hub_strategy: EVERY_SAVE
            hub_token: null
            ignore_data_skip: false
            include_inputs_for_metrics: false
            jit_mode_eval: false
            label_names: null
            label_smoothing_factor: 0
            learning_rate: 0.0004
            length_column_name: length
            load_best_model_at_end: true
            local_rank: 0
            log_level: passive
            log_level_replica: warning
            log_on_each_node: true
            logging_dir: runs/esm_650m_ecoli_finetuning/runs/Mar17_01-04-55_kg03-p
            logging_first_step: false
            logging_nan_inf_filter: true
            logging_steps: 500
            logging_strategy: STEPS
            lr_scheduler_type: COSINE
            max_grad_norm: 1
            max_steps: -1
            metric_for_best_model: loss
            mp_parameters: ""
            no_cuda: false
            num_train_epochs: 100
            optim: ADAMW_HF
            optim_args: null
            output_dir: runs/esm_650m_ecoli_finetuning
            overwrite_output_dir: false
            past_index: -1
            per_device_eval_batch_size: 16
            per_device_train_batch_size: 16
            per_gpu_eval_batch_size: null
            per_gpu_train_batch_size: null
            prediction_loss_only: false
            push_to_hub: false
            push_to_hub_model_id: null
            push_to_hub_organization: null
            push_to_hub_token: null
            ray_scope: last
            remove_unused_columns: false
            report_to:
                - wandb
            resume_from_checkpoint: null
            run_name: ESM2-650M-run-2
            save_on_each_node: false
            save_safetensors: false
            save_steps: 500
            save_strategy: STEPS
            save_total_limit: 1
            seed: 42
            sharded_ddp: []
            skip_memory_metrics: true
            tf32: null
            torch_compile: false
            torch_compile_backend: null
            torch_compile_mode: null
            torchdynamo: null
            tpu_metrics_debug: false
            tpu_num_cores: null
            use_ipex: false
            use_legacy_prediction_loop: false
            use_mps_device: false
            warmup_ratio: 0
            warmup_steps: 1000
            weight_decay: 0.01
            xpu_backend: null
        wandb_project: esm_650m_ecoli_finetuning
